#!name=QX-Resource-Review
#!desc=คัดลิงก์นำเข้าแบบคลิกเดียวจาก qx แล้วเปิดใน Safari เพื่อดูตัวอย่าง

[Script]
qx-resource-preview = type=http-request, pattern=^https:\/\/quantumult\.app\/x\/open-app\/add-resource\?remote-resource=, script-path=https://github.com/chengkongyiban/shadowrocket/raw/main/scripts/qx-resource-preview.js, requires-body=true, max-size=-1, timeout=60

[MITM]
hostname = %APPEND% quantumult.app